Fix the labeling of subdomain boundary faces
hpgem/hpgem pull request #53
Opened 2020-08-28 13:11 UTC by Laar

The current check is to look if the same (by id) global nodes are both
side of the face. This identical to checking their coordinates but
independent of the dimension. This differs from the previous version
where no only the node coordinates were checked, but also their
ordering (which does not need to be the same on both sides).

2020-08-31 08:07 UTC, JensWehner requested changes
Nice change, makes the code more readable, but it should still be a function.

2020-08-31 08:07 UTC, JensWehner commented on kernel/Base/Face.cpp
> +    }
this should be a function.

2020-08-31 08:07 UTC, JensWehner requested changes
Nice, changes, make the code more readable. Can you refactor it into a function

2020-08-31 09:19 UTC, Laar commented
Part of the reason for leaving it inline was that the function does not determine what type of periodic boundary face it is, i.e., subdomain or not. Currently I'm not wanting to change too much to prevent it accidentally breaking.

I hope that if we refactor the Mesh that this will be improved a lot.

2020-10-23 10:50 UTC, JensWehner requested changes
@Laar good refactor, just a small spelling mistake and `const` stuff

2020-10-23 10:50 UTC, JensWehner commented on kernel/Base/Face.cpp
> +    if (detirmineIsPeriodicBoundaryFace()) {
fix spelling pls.
```suggestion
    if (determineIsPeriodicBoundaryFace()) {
```

2020-10-23 10:50 UTC, JensWehner commented on kernel/Base/Face.cpp
> +    if (detirmineIsPeriodicBoundaryFace()) {
```suggestion
    if (determineIsPeriodicBoundaryFace()) {
```

2020-10-23 10:50 UTC, JensWehner commented on kernel/Base/Face.cpp
> +bool Face::detirmineIsPeriodicBoundaryFace() {
```suggestion
bool Face::determineIsPeriodicBoundaryFace() {
```

2020-10-23 10:50 UTC, JensWehner commented on kernel/Base/Face.h
> +    bool detirmineIsPeriodicBoundaryFace();
should be const 
```suggestion
    bool determineIsPeriodicBoundaryFace()const;
```

2020-10-23 11:50 UTC, Laar commented
> @Laar good refactor, just a small spelling mistake and `const` stuff

@JensWehner Done, needed a little more formatting (and the `const` in the cpp file).

2020-10-23 13:59 UTC, JensWehner approved these changes
LGTM

2020-10-23 14:48 UTC, merged